### ISSUE TITLE
Missing Toggler Component

### ISSUE THREAD

**Issue by jonnilundy** [wedeploy/generator-electric#2]
No toggler component found for docs sidebar. 
bundle.js missing.

**Comment by robframpton** [comment]
Can you provide more information? Was this after creating a new site?

**Comment by jonnilundy** [comment]
We are trying to fix the toggler function for the Docs Sidebar because it is currently inactive on mine. We went to this repo to reference the bundle.js file to find the function but there is no bundle.js in this repo that we could find.

**Comment by robframpton** [comment]
The `bundle.js` file is generated so you won't find it committed anywhere.

I removed the SideBar component in this [commit](https://github.com/Robert-Frampton/electric-components/commit/d9e172b01937320a9e73d388026f7f5ad381426e) because it makes more sense to exist in the site itself. When you added the .sidebar template to your layout file we probably didn't port over the small js file as well.

What you can do is take the .sidebar portion of your layout and make it into a component that invokes the toggler. I'm going to add it into the generator so you can just copy it from there once I'm done.

**Comment by robframpton** [comment]
7dd351aefeba84a9fa97c8506337e4bb5804ddaf
