### ISSUE TITLE
Senna navigation doesn't work with HTTPS

### ISSUE THREAD

**Issue by pragmaticivan** [wedeploy/generator-electric#31]
The links shows as https, but the request is going with only http. I get navigation errors after that.

**Comment by pragmaticivan** [comment]
@ygorcosta, @zenorocha  this one is pretty critical.

**Comment by pragmaticivan** [comment]
<img width="1440" alt="screen shot 2017-04-03 at 7 47 02 pm" src="https://cloud.githubusercontent.com/assets/301291/24639716/8e7eb7b6-18a6-11e7-8801-60cf3463894e.png">

**Comment by pragmaticivan** [comment]
Just tested again with the new version. Still happening. I created this one from scratch.

**Comment by eduardolundgren** [comment]
Senna does support HTTPS, see https://github.com/liferay/senna.js/pull/157. Electric might be doing something that breaks the functionality.

**Comment by fernandosouza** [comment]
This happens because the link to the page that should be loaded is not using `https` protocol.
[https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content)

I've just created a new electric project and I've seen that links there are relative, it should work.

**Comment by zenorocha** [comment]
Fixed on https://github.com/liferay/senna.js/commit/cf155d41ebe70a7813a090729d1b67e2d5859879
